# -*- coding: utf-8 -*-
"""Votingmanagement.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QyUr9GkHBdumY2cJhWdRUnGnftNClzIU
"""

import hashlib
import time

class Block:
    def __init__(self, index, transactions, previous_hash):
        self.index = index
        self.timestamp = time.time()
        self.transactions = transactions
        self.previous_hash = previous_hash
        self.hash = self.calculate_hash()

    def calculate_hash(self):
        block_string = f"{self.index}{self.timestamp}{self.transactions}{self.previous_hash}"
        return hashlib.sha256(block_string.encode()).hexdigest()


class Blockchain:
    def __init__(self):
        self.chain = [self.create_genesis_block()]

    def create_genesis_block(self):
        return Block(0, "Genesis Block", "0")

    def get_latest_block(self):
        return self.chain[-1]

    def add_block(self, transactions):
        previous_hash = self.get_latest_block().hash
        new_block = Block(len(self.chain), transactions, previous_hash)
        self.chain.append(new_block)

    def print_chain(self):
        for block in self.chain:
            print("\n----------------------")
            print(f"Index: {block.index}")
            print(f"Timestamp: {block.timestamp}")
            print(f"Transactions: {block.transactions}")
            print(f"Previous Hash: {block.previous_hash}")
            print(f"Hash: {block.hash}")
        print("\n----------------------")

    def is_chain_valid(self):
        for i in range(1, len(self.chain)):
            current = self.chain[i]
            previous = self.chain[i - 1]

            if current.hash != current.calculate_hash():
                return False
            if current.previous_hash != previous.hash:
                return False
        return True


voters = {}
candidates = {}

blockchain = Blockchain()



def add_candidate():
    cid = input("Enter Candidate ID: ")
    if cid in candidates:
        print(" Candidate already exists!")
        return
    name = input("Enter Candidate Name: ")
    candidates[cid] = name
    print(" Candidate added successfully")


def add_voter():
    vid = input("Enter Voter ID: ")
    if vid in voters:
        print(" Voter already exists!")
        return
    name = input("Enter Voter Name: ")
    voters[vid] = {"name": name, "has_voted": False}
    print(" Voter added successfully")


def cast_vote():
    vid = input("Enter Voter ID: ")
    if vid not in voters:
        print("Voter not found!")
        return

    if voters[vid]["has_voted"]:
        print(" Voter has already voted!")
        return

    print("Candidates:")
    for cid, name in candidates.items():
        print(f"{cid}: {name}")

    cid = input("Enter Candidate ID to vote: ")
    if cid not in candidates:
        print(" Invalid candidate!")
        return

    transaction = f"{voters[vid]['name']} voted for {candidates[cid]}"
    blockchain.add_block(transaction)

    voters[vid]["has_voted"] = True
    print(" Vote cast successfully!")


def validate_chain():
    if blockchain.is_chain_valid():
        print("Blockchain is valid")
    else:
        print(" Blockchain is tampered!")


def menu():
    while True:
        print("\n====== Voting Blockchain System ======")
        print("1. Add Candidate")
        print("2. Add Voter")
        print("3. Cast Vote")
        print("4. Print Blockchain")
        print("5. Validate Chain")
        print("6. Exit")

        choice = input("Enter your choice: ")

        if choice == "1":
            add_candidate()
        elif choice == "2":
            add_voter()
        elif choice == "3":
            cast_vote()
        elif choice == "4":
            blockchain.print_chain()
        elif choice == "5":
            validate_chain()
        elif choice == "6":
            print("Exiting...")
            break
        else:
            print("Invalid choice!")



menu()